
LARGEUR_ECRAN = 800
HAUTEUR_ECRAN = 700
LARGEUR_GRILLE_PIXEL = 300  # meaning 300 // 10 = 30 width per block
HAUTEUR_GRILLE_PIXEL = 600  # meaning 600 // 20 = 30 height per block
TAILLE_BLOC = 30
HAUT_GAUCHE_X = (LARGEUR_ECRAN - LARGEUR_GRILLE_PIXEL) // 2
HAUT_GAUCHE_Y = HAUTEUR_ECRAN - HAUTEUR_GRILLE_PIXEL

